# Generated by Django 5.1.7 on 2026-08-03 18:11

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='comments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
