# Generated by Django 5.0.1 on 2025-04-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Xem'), ('like', 'Thích'), ('comment', 'Bình luận'), ('share', 'Chia sẻ'), ('save', 'Lưu'), ('click', 'Click vào chi tiết')], max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Thời gian tương tác tính bằng giây')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tương tác người dùng',
                'verbose_name_plural': 'Tương tác người dùng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='posts_useri_user_id_e0ea22_idx'), models.Index(fields=['post', 'interaction_type'], name='posts_useri_post_id_80f76e_idx')],
            },
        ),
    ]
