# Generated by Django 5.1.7 on 2026-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comments/videos/%Y/%m/', verbose_name='video'),
        ),
    ]
