# Generated by Django 5.0.1 on 2025-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commentlike_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='posts/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='posts', verbose_name='file'),
        ),
    ]
