# Generated by Django 5.0.1 on 2025-04-14 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_shared_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='admin notes'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='resolved'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True, verbose_name='valid report'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolved at'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_post_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
