# Generated by Django 5.1.7 on 2026-08-11 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='viral_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='viral_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-viral_score', '-created_at'], name='posts_post_viral_s_94d209_idx'),
        ),
    ]
