# Generated by Django 5.1.7 on 2026-08-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_viral_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_promoted',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin đẩy viral — hiện badge & ưu tiên feed trending'),
        ),
        migrations.AddField(
            model_name='post',
            name='admin_viral_boost',
            field=models.FloatField(default=0.0, help_text='Sàn điểm viral khi được admin promote (0 = dùng mặc định ~80)'),
        ),
    ]
