# Generated by Django 5.1.7 on 2026-08-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_admin_viral_promote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('only_me', 'Only me')], db_index=True, default='public', help_text='Who can see this post', max_length=16),
        ),
    ]
