"""
Django settings for hoshi project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
# Load .env (ưu tiên hơn biến môi trường shell tạm — tránh kẹt SQLite khi dump)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / '.env', override=True)
except ImportError:
    pass

# Không sử dụng decouple, truy cập trực tiếp vào os.environ
def config(key, default=None, cast=None):
    value = os.environ.get(key, default)
    if cast and value is not None and value != default:
        if cast == bool:
            return str(value).lower() in ('true', 'yes', '1')
        return cast(value)
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    config('SECRET_KEY', default='')
    or config('DJANGO_SECRET_KEY', default='')
    or 'dev-only-insecure-key-change-me'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=None)
if DEBUG is None:
    DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)
else:
    DEBUG = str(DEBUG).lower() in ('true', 'yes', '1')

_raw_hosts = (
    config('ALLOWED_HOSTS', default='')
    or config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1')
)
ALLOWED_HOSTS = [h.strip() for h in str(_raw_hosts).split(',') if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Local DEBUG: nhận mọi Host (IP đổi / ĐT vào bằng IP / ngrok) — không cần sửa .env
# Production (DEBUG=False): BẮT BUỘC liệt kê domain thật, không dùng '*'.
if DEBUG:
    ALLOWED_HOSTS = ['*']

# CSRF — cấu hình qua env; local + ngrok khi DEBUG
_raw_csrf = (
    config('CSRF_TRUSTED_ORIGINS', default='')
    or config('DJANGO_CSRF_TRUSTED_ORIGINS', default='')
)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in str(_raw_csrf).split(',') if o.strip()]
if DEBUG:
    for origin in (
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'https://*.ngrok-free.app',
        'https://*.ngrok-free.dev',
        'https://*.ngrok.io',
    ):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)
    # Origin theo IP bất kỳ được nới bằng DebugOpenHostMiddleware (dưới)

# Application definition

INSTALLED_APPS = [
    # Admin theme (phải trước django.contrib.admin)
    'admin_interface',
    'colorfield',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'channels',
    'django_cleanup.apps.CleanupConfig',
    'imagekit',
    'django_filters',
    'taggit',
    'phonenumber_field',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    
    # Local apps
    'hoshi.apps.HoshiConfig',
    'accounts.apps.AccountsConfig',
    'posts.apps.PostsConfig',
    'chat.apps.ChatConfig',
    'notifications.apps.NotificationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # DEBUG: cho phép đăng nhập/POST từ mọi IP/Host mà không sửa CSRF_TRUSTED_ORIGINS
    'accounts.middleware.DebugOpenHostMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.UserLanguageMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.AccountStatusMiddleware',
    'accounts.middleware.TwoFactorPendingMiddleware',
    'accounts.middleware.DeviceTrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'accounts/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'hoshi.context_processors.common_variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'hoshi.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Ưu tiên DATABASE_URL (Postgres). Không có / sqlite → dùng db.sqlite3.

DATABASE_URL = (config('DATABASE_URL', default='') or '').strip()


def _database_from_url(url: str):
    """Parse postgres:// hoặc postgresql:// thành dict Django DATABASES."""
    from urllib.parse import urlparse, unquote

    parsed = urlparse(url)
    scheme = (parsed.scheme or '').lower()
    if scheme not in ('postgres', 'postgresql'):
        return None
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote((parsed.path or '/').lstrip('/') or 'hoshi'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': str(parsed.port or 5432),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }


_pg = _database_from_url(DATABASE_URL) if DATABASE_URL else None
if _pg:
    DATABASES = {'default': _pg}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'vi'

LANGUAGES = [
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
    ('ja', '日本語'),
    ('ko', '한국어'),
    ('zh-hans', '简体中文'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'account_login'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# AllAuth settings
SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_PRESERVE_USERNAME_CASING = False
# ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.CustomSignupForm'

# Thêm cấu hình ACCOUNT_FORMS
ACCOUNT_FORMS = {
    "login": "allauth.account.forms.LoginForm",
    "add_email": "allauth.account.forms.AddEmailForm",
    "change_password": "allauth.account.forms.ChangePasswordForm",
    "set_password": "allauth.account.forms.SetPasswordForm",
    "reset_password": "accounts.forms.CustomResetPasswordForm",
    "reset_password_from_key": "accounts.forms.CustomResetPasswordKeyForm",
    "disconnect": "allauth.socialaccount.forms.DisconnectForm",
    "signup": "accounts.forms.CustomSignupForm",
}

# Email settings — chỉ lấy từ env (không hardcode mật khẩu)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = int(config('EMAIL_PORT', default='587') or 587)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
SITE_NAME = config('SITE_NAME', default='Moora')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Moora <noreply@moora.vn>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Phone numbers
PHONENUMBER_DB_FORMAT = 'E164'
PHONENUMBER_DEFAULT_REGION = None

# Twilio SMS for phone OTP 
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM_NUMBER = config('TWILIO_FROM_NUMBER', default='')

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('DRF_THROTTLE_ANON', default='60/min'),
        'user': config('DRF_THROTTLE_USER', default='300/min'),
    },
}

# Closed beta: bắt buộc mã mời khi đăng ký (mặc định bật nếu không DEBUG)
_invite = config('INVITE_ONLY', default=None)
if _invite is None:
    INVITE_ONLY = not DEBUG
else:
    INVITE_ONLY = str(_invite).lower() in ('true', 'yes', '1')

# Channels / cache — dùng Redis nếu có và đang chạy; không thì InMemory (dev local)
REDIS_URL = config('REDIS_URL', default='').strip()

def _redis_reachable(url: str) -> bool:
    if not url:
        return False
    try:
        import redis
        client = redis.Redis.from_url(url, socket_connect_timeout=1, socket_timeout=1)
        client.ping()
        client.close()
        return True
    except Exception:
        return False


USE_REDIS = bool(REDIS_URL) and _redis_reachable(REDIS_URL)

if not DEBUG:
    # Production: bắt buộc Postgres + Redis
    if 'sqlite' in DATABASES['default']['ENGINE']:
        raise ImproperlyConfigured(
            'Production (DEBUG=False) yêu cầu PostgreSQL. Đặt DATABASE_URL=postgres://...'
        )
    if not REDIS_URL:
        raise ImproperlyConfigured(
            'Production (DEBUG=False) yêu cầu REDIS_URL (cache + Channels).'
        )
    if not USE_REDIS:
        raise ImproperlyConfigured(
            f'Không kết nối được Redis tại {REDIS_URL}. Bật Redis trước khi chạy production.'
        )
    if SECRET_KEY.startswith('dev-only') or SECRET_KEY in (
        'your-secret-key-here',
        'django-insecure-key-for-build-only',
    ):
        raise ImproperlyConfigured('Production cần SECRET_KEY / DJANGO_SECRET_KEY mạnh.')

if REDIS_URL and not USE_REDIS:
    import logging
    logging.getLogger(__name__).warning(
        'REDIS_URL=%s nhưng không kết nối được — dùng InMemoryChannelLayer / LocMemCache.',
        REDIS_URL,
    )

if USE_REDIS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = False if DEBUG else True
SESSION_SAVE_EVERY_REQUEST = False

# Security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'

# Social account providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'APP': {
            'client_id': config('FACEBOOK_CLIENT_ID', default=''),
            'secret': config('FACEBOOK_CLIENT_SECRET', default=''),
            'key': ''
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'vi_VN',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    },
    'apple': {
        'APP': {
            'client_id': config('APPLE_CLIENT_ID', default=''),
            'secret': config('APPLE_CLIENT_SECRET', default=''),
            'key': config('APPLE_KEY_ID', default=''),
            'settings': {
                'certificate_key': config('APPLE_CERTIFICATE_KEY', default='')
            }
        }
    }
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'posts': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# AllAuth settings
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'

# Template overrides cho django-allauth
ACCOUNT_TEMPLATE_EXTENSION = 'html'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGIN_URL
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None

# Cấu hình email HTML
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
# optional: vẫn tạo EmailAddress, nhưng không bắt buộc xác minh để dùng app
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180
ACCOUNT_EMAIL_MAX_LENGTH = 254

# Cho phép gửi email HTML
ACCOUNT_EMAIL_CONFIRMATION_EMAIL_TEMPLATE = "account/email/email_confirmation_message.html"
ACCOUNT_PASSWORD_RESET_EMAIL_TEMPLATE = "account/email/password_reset_key_message.html"
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180

# Vô hiệu hóa những cảnh báo không cần thiết
SILENCED_SYSTEM_CHECKS = ['allauth.socialaccount.W002']

# File upload settings (mặc định 50MB — chỉnh bằng MAX_UPLOAD_MB trong .env)
_MAX_UPLOAD_MB = int(config('MAX_UPLOAD_MB', default='50') or 50)
MAX_UPLOAD_SIZE = max(_MAX_UPLOAD_MB, 1) * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = min(MAX_UPLOAD_SIZE, 10 * 1024 * 1024)  # giữ body nhỏ trong RAM
FILE_UPLOAD_MAX_MEMORY_SIZE = min(MAX_UPLOAD_SIZE, 10 * 1024 * 1024)
CONTENT_TYPES = [
    'image/jpeg', 'image/png', 'image/gif', 'image/webp',
    'video/mp4', 'video/quicktime', 'video/x-matroska', 'video/webm', 'video/avi',
]

# Media: S3/R2 khi có credentials THẬT (bỏ qua placeholder your-*)
def _aws_looks_real(value: str) -> bool:
    v = (value or '').strip()
    if not v:
        return False
    low = v.lower()
    if low.startswith('your-') or low in {
        'changeme',
        'todo',
        'xxx',
        'your-aws-access-key',
        'your-aws-secret-key',
        'your-bucket-name',
        'your-region',
    }:
        return False
    return True


AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='').strip()
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='').strip()
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='').strip()
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-southeast-1').strip()
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='').strip() or None
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='').strip() or None
AWS_DEFAULT_ACL = None  # bucket policy quyết định, tránh public-read mặc định
AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=True, cast=bool)
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_S3_FILE_OVERWRITE = False

USE_S3_MEDIA = all(
    _aws_looks_real(x)
    for x in (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME)
)

if USE_S3_MEDIA:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f'{AWS_S3_ENDPOINT_URL.rstrip("/")}/{AWS_STORAGE_BUCKET_NAME}/'
elif not DEBUG:
    import logging
    logging.getLogger(__name__).warning(
        'DEBUG=False nhưng chưa cấu hình S3/R2 thật — media vẫn lưu local disk.'
    )

# Sentry (optional)
SENTRY_DSN = config('SENTRY_DSN', default='').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(config('SENTRY_TRACES_SAMPLE_RATE', default='0.1') or 0.1),
            send_default_pii=False,
            environment='production' if not DEBUG else 'development',
        )
    except ImportError:
        pass

# Custom settings
POSTS_PER_PAGE = 20
NOTIFICATIONS_PER_PAGE = 15
MESSAGES_PER_PAGE = 20

# WebRTC ICE / TURN tự host (coturn) — xem huong_dan_turn.txt
# TURN_HOST=IP_hoac_domain
# TURN_USERNAME=moora
# TURN_CREDENTIAL=...
# TURN_EXTERNAL_IP=...  (cho docker coturn)
TURN_URLS = config('TURN_URLS', default='').strip()
TURN_HOST = config('TURN_HOST', default='').strip()
TURN_USERNAME = config('TURN_USERNAME', default='').strip()
TURN_CREDENTIAL = config('TURN_CREDENTIAL', default='').strip()
TURN_SECRET = config('TURN_SECRET', default='').strip()
TURN_CREDENTIAL_TTL = int(config('TURN_CREDENTIAL_TTL', default='3600') or 3600)
ICE_SERVERS_JSON = config('ICE_SERVERS_JSON', default='').strip()
METERED_TURN_API_KEY = config('METERED_TURN_API_KEY', default='').strip()
METERED_TURN_APP_NAME = config('METERED_TURN_APP_NAME', default='').strip()
METERED_TURN_CREDENTIALS_URL = config('METERED_TURN_CREDENTIALS_URL', default='').strip()
WEBRTC_ICE_TRANSPORT_POLICY = config('WEBRTC_ICE_TRANSPORT_POLICY', default='all').strip()
WEBRTC_PREFER_RELAY = config('WEBRTC_PREFER_RELAY', default=False, cast=bool)
