version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hoshi
      - POSTGRES_PASSWORD=hoshipassword
      - POSTGRES_DB=hoshi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoshi"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-for-local-development
      - DATABASE_URL=postgres://hoshi:hoshipassword@db:5432/hoshi
      - DJANGO_SETTINGS_MODULE=hoshi.settings_railway
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume: 