# Generated by Django 4.2 on 2025-04-15 17:56

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.message_file_path),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.message_file_path),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.message_file_path),
        ),
    ]
