# Generated by Django 5.0.1 on 2025-03-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
