# Generated by Django 5.1.7 on 2026-08-03 18:21

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationmessage_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.message_file_path),
        ),
    ]
