# Generated by Django 5.0.1 on 2025-03-21 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_vanish_mode',
            field=models.BooleanField(default=False, help_text='Tin nhắn sẽ biến mất sau khi xem'),
        ),
        migrations.AddField(
            model_name='chatroomparticipant',
            name='is_accepted',
            field=models.BooleanField(default=True, help_text='Đã chấp nhận lời mời trò chuyện'),
        ),
        migrations.AddField(
            model_name='chatroomparticipant',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='Tắt thông báo'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Tin nhắn đã xóa'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_vanished',
            field=models.BooleanField(default=False, help_text='Tin nhắn đã biến mất (vanish mode)'),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('reaction', 'Reaction'), ('story_reply', 'Story Reply'), ('voice', 'Voice Message')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '❤️'), ('laugh', '😂'), ('sad', '😢'), ('angry', '😡'), ('wow', '😮'), ('thumbs_up', '👍'), ('thumbs_down', '👎')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
