# Generated by Django 5.1.7 on 2026-08-04 17:11

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.group_avatar_path),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
