# Generated by Django 5.1.7 on 2026-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_group_admin_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
