# Generated by Django 5.1.7 on 2026-08-11 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='deleted_for_everyone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='is_deleted_for_everyone',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
