# Generated by Django 5.1.7 on 2026-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_delete_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
