# Generated by Django 5.0.4 on 2025-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='inactive_notifications',
            field=models.BooleanField(default=False, verbose_name='inactive notifications'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='summary_notifications',
            field=models.BooleanField(default=False, verbose_name='summary notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='inactive_notifications',
            field=models.BooleanField(default=False, verbose_name='inactive notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='summary_notifications',
            field=models.BooleanField(default=False, verbose_name='summary notifications'),
        ),
    ]
