# Generated by Django 5.0.1 on 2025-04-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_is_verified'),
        ('accounts', 'fix_is_verified'),
    ]

    operations = [
    ]
