# Generated by Django 5.0.4 on 2025-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser_inactive_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='comment_notifications',
            field=models.BooleanField(default=True, verbose_name='comment notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='follow_notifications',
            field=models.BooleanField(default=True, verbose_name='follow notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='inactive_notifications',
            field=models.BooleanField(default=True, verbose_name='inactive notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='like_notifications',
            field=models.BooleanField(default=True, verbose_name='like notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='mention_notifications',
            field=models.BooleanField(default=True, verbose_name='mention notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='message_notifications',
            field=models.BooleanField(default=True, verbose_name='message notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='push notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='summary_notifications',
            field=models.BooleanField(default=True, verbose_name='summary notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment_notifications',
            field=models.BooleanField(default=True, verbose_name='comment notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow_notifications',
            field=models.BooleanField(default=True, verbose_name='follow notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inactive_notifications',
            field=models.BooleanField(default=True, verbose_name='inactive notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_notifications',
            field=models.BooleanField(default=True, verbose_name='like notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mention_notifications',
            field=models.BooleanField(default=True, verbose_name='mention notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_notifications',
            field=models.BooleanField(default=True, verbose_name='message notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='push notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='summary_notifications',
            field=models.BooleanField(default=True, verbose_name='summary notifications'),
        ),
    ]
