# Generated by Django 5.0.1 on 2025-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-followed_at'], 'verbose_name': 'following', 'verbose_name_plural': 'followings'},
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
