# Generated by Django 5.0.1 on 2025-03-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userfollowing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created_at'], 'verbose_name': 'following', 'verbose_name_plural': 'followings'},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='followed_at',
        ),
    ]
