# Generated by Django 5.0.1 on 2025-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_fix_is_verified_fix_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False, verbose_name='verified account'),
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='is_verified',
            new_name='_is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False, verbose_name='verified account'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='_is_verified',
        ),
    ]
