# Generated by Django 5.1.7 on 2026-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_historicaluser_comment_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='two-factor secret'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='two-factor secret'),
        ),
    ]
