# Generated by Django 5.1.7 on 2026-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English'), ('ja', '日本語'), ('ko', '한국어'), ('zh-hans', '简体中文')], default='vi', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English'), ('ja', '日本語'), ('ko', '한국어'), ('zh-hans', '简体中文')], default='vi', max_length=10, verbose_name='language'),
        ),
    ]
