# Generated by Django 5.0.1 on 2025-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_is_verified_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='message_notifications',
            field=models.BooleanField(default=False, verbose_name='message notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_notifications',
            field=models.BooleanField(default=False, verbose_name='message notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='comment_notifications',
            field=models.BooleanField(default=False, verbose_name='comment notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='follow_notifications',
            field=models.BooleanField(default=False, verbose_name='follow notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='like_notifications',
            field=models.BooleanField(default=False, verbose_name='like notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='mention_notifications',
            field=models.BooleanField(default=False, verbose_name='mention notifications'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='push notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment_notifications',
            field=models.BooleanField(default=False, verbose_name='comment notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow_notifications',
            field=models.BooleanField(default=False, verbose_name='follow notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_notifications',
            field=models.BooleanField(default=False, verbose_name='like notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mention_notifications',
            field=models.BooleanField(default=False, verbose_name='mention notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='push notifications'),
        ),
    ]
