# Generated by Django 5.0.1 on 2025-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='suspended account'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suspension end date'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='suspension reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='suspended account'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suspension end date'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='suspension reason'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='admin notes'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True, verbose_name='valid report'),
        ),
    ]
