# Generated by Django 5.1.7 on 2026-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location_accuracy_m',
            field=models.FloatField(blank=True, help_text='Độ lệch ước tính (mét)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='location_source',
            field=models.CharField(blank=True, choices=[('gps', 'GPS / trình duyệt'), ('ip', 'Địa chỉ IP'), ('manual', 'Thủ công')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
