# Generated by Django 5.0.1 on 2025-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historicaluser_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True, verbose_name='deletion reason'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted account'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True, verbose_name='deletion reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted account'),
        ),
    ]
