# Generated by Django 5.1.7 on 2026-08-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='show_birth_date',
            field=models.BooleanField(default=False, help_text='If enabled, birth date is visible on your public profile.', verbose_name='show birth date on profile'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='show_gender',
            field=models.BooleanField(default=False, help_text='If enabled, gender is visible on your public profile.', verbose_name='show gender on profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=False, help_text='If enabled, birth date is visible on your public profile.', verbose_name='show birth date on profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_gender',
            field=models.BooleanField(default=False, help_text='If enabled, gender is visible on your public profile.', verbose_name='show gender on profile'),
        ),
    ]
